import { isAnalysisFailure } from "../../domain/analysis-status.js";
import { DiffWitnessError } from "../../domain/errors.js";
import { parseExplanation } from "../../domain/schemas.js";
import type {
  EvidencePacket,
  Explanation,
  ExplanationCitation,
  ExplanationFact,
  ExplanationHypothesis,
} from "../../domain/types.js";
import type { AiProvider, ExplainOptions } from "../../ports/ai-provider.js";
import {
  EXPLAIN_PROMPT_VERSION,
  EXPLAIN_SYSTEM_PROMPT,
  buildExplainUserPrompt,
} from "./prompts/explain.v2.js";
import {
  CAUSALITY_CAVEAT,
  changeSurfaceFact,
  changeSurfaceNarrative,
  hypothesisClaim,
} from "./mock-change-surface-text.js";

/**
 * Deterministic offline AI provider. Explains packet facts only; never executes tools.
 * Same packet → same Explanation. No fs / network / process.
 */
export class MockAIProvider implements AiProvider {
  readonly name = "mock";

  /** Exposed for tests — proves prompts are versioned product logic. */
  readonly promptVersion = EXPLAIN_PROMPT_VERSION;

  async explain(packet: EvidencePacket, opts?: ExplainOptions): Promise<Explanation> {
    // Touch versioned prompts so they cannot drift unused (determinism still ignores live LLM).
    void EXPLAIN_SYSTEM_PROMPT;
    void buildExplainUserPrompt(JSON.stringify(packet));

    const modelId = opts?.modelId ?? "mock-v1";

    if (isAnalysisFailure(packet.status)) {
      return parseExplanation({
        schemaVersion: 1,
        promptVersion: EXPLAIN_PROMPT_VERSION,
        narrative: [
          "FACT: Analysis status is analysis_error.",
          "EVIDENCE: packet.status=analysis_error (no trustworthy BehavioralDiff findings to narrate).",
          "INTERPRETATION: DiffWitness refuses to claim a clean behavioral bill of health.",
        ].join("\n"),
        facts: [
          {
            claim: "Analysis did not complete successfully (status=analysis_error).",
            evidenceIds: [],
          },
        ],
        hypotheses: [],
        citations: [],
        caveats: [
          "status is analysis_error — treat as incomplete analysis, not absence of regressions",
          "Generated by MockAIProvider — deterministic template, no live model.",
        ],
        modelId,
        provider: this.name,
      });
    }

    if (packet.status === "clean" || packet.findings.length === 0) {
      return parseExplanation({
        schemaVersion: 1,
        promptVersion: EXPLAIN_PROMPT_VERSION,
        narrative: [
          "FACT: No behavioral findings are present in the EvidencePacket.",
          "EVIDENCE: findings=[]",
          "INTERPRETATION: Nothing behavioral to explain — DiffEngine reported clean / empty findings.",
        ].join("\n"),
        facts: [
          {
            claim: "No behavioral findings were present in the evidence packet.",
            evidenceIds: [],
          },
        ],
        hypotheses: [],
        citations: [],
        caveats: [
          "Explanation is bound to the supplied EvidencePacket only.",
          "Generated by MockAIProvider — deterministic template, no live model.",
        ],
        modelId,
        provider: this.name,
      });
    }

    const surface = packet.changeSurface;
    const findingFacts: ExplanationFact[] = packet.findings.map((f) => ({
      claim: `[${f.id}] ${f.summary} (${f.findingType}; ${f.change}; severity=${f.severity})`,
      findingId: f.id,
      evidenceIds: [...f.evidenceIds],
    }));
    const facts: ExplanationFact[] =
      surface !== undefined ? [...findingFacts, changeSurfaceFact(surface)] : findingFacts;

    const hypotheses: ExplanationHypothesis[] = packet.findings.map((f) => ({
      claim: hypothesisClaim(f.workflowId, f.observationKey, surface),
      confidence: severityToConfidence(f.severity),
      findingId: f.id,
      evidenceIds: [...f.evidenceIds],
    }));

    const citations: ExplanationCitation[] = packet.findings.map((f) => ({
      findingId: f.id,
      claim: f.summary,
      ...(f.evidenceIds[0] !== undefined ? { evidenceId: f.evidenceIds[0] } : {}),
    }));

    const factLines = findingFacts.map((f) => `- ${f.claim} [evidence: ${f.evidenceIds.join(", ")}]`);
    const evidenceLines = packet.evidenceExcerpts.map(
      (e) => `- ${e.evidenceId} ${e.observationKey} digest=${e.digest} preview=${JSON.stringify(e.preview)}`,
    );
    const hypLines = hypotheses.map(
      (h) => `- (${h.confidence}) ${h.claim} [evidence: ${h.evidenceIds.join(", ")}]`,
    );

    const narrative = [
      "FACT:",
      ...factLines,
      "EVIDENCE:",
      ...(evidenceLines.length > 0 ? evidenceLines : ["- (no excerpts in packet)"]),
      ...(surface !== undefined ? changeSurfaceNarrative(surface) : []),
      "INTERPRETATION:",
      ...hypLines,
    ].join("\n");

    return parseExplanation({
      schemaVersion: 1,
      promptVersion: EXPLAIN_PROMPT_VERSION,
      narrative,
      facts,
      hypotheses,
      citations,
      caveats: [
        "Generated by MockAIProvider — deterministic template, no live model.",
        "Claims are limited to EvidencePacket contents.",
        "Hypotheses are speculative; DiffEngine owns pass/fail and findings.",
        ...(surface !== undefined ? [CAUSALITY_CAVEAT] : []),
        `promptVersion=${EXPLAIN_PROMPT_VERSION}`,
      ],
      modelId,
      provider: this.name,
    });
  }
}

function severityToConfidence(severity: "info" | "warn" | "error"): "low" | "medium" | "high" {
  if (severity === "error") {
    return "high";
  }
  if (severity === "warn") {
    return "medium";
  }
  return "low";
}

/** Guard: providers must not gain execution / repo / search APIs. */
export function assertProviderIsExplainOnly(provider: AiProvider): void {
  const forbidden = [
    "run",
    "exec",
    "execute",
    "runCommand",
    "shell",
    "spawn",
    "git",
    "readFile",
    "writeFile",
    "search",
  ] as const;
  const record = provider as unknown as Record<string, unknown>;
  for (const key of forbidden) {
    if (typeof record[key] === "function") {
      throw new DiffWitnessError("provider", `AiProvider must not expose ${key}()`);
    }
  }
  const proto = Object.getPrototypeOf(provider) as object | null;
  if (proto !== null) {
    for (const key of forbidden) {
      const desc = Object.getOwnPropertyDescriptor(proto, key);
      if (desc !== undefined && typeof desc.value === "function") {
        throw new DiffWitnessError("provider", `AiProvider must not expose ${key}()`);
      }
    }
  }
  if ("repositoryPath" in record && record.repositoryPath !== undefined) {
    throw new DiffWitnessError("provider", "AiProvider must not receive repositoryPath");
  }
}
